name: hanime-auto-coins

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3,18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: pip install -r ./requirements.txt

      - name: Set up Environment
        run: |
          echo "hanime_email=${{ secrets.HANIME_EMAIL }}" > .env
          echo "hanime_password=${{ secrets.HANIME_PASSWORD }}" >> .env
          echo "webhook_url=${{ secrets.WEBHOOK_URL }}" >> .env

      - name: Working
        run: |
          python ./AIO.py
